import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import { Paragraph } from "../components/Paragraph";
import { SectionTitle } from "../components/SectionTitle";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SectionTitle>Animación y conducción de eventos</SectionTitle>
        <Paragraph>
          Organizamos bailes en clubes, para el día del amigo, día la primavera,
          fin Etc. Completamos con otros servicios profesionales para ocasiones
          especiales: Animación de eventos, fotografías y vídeos. Magia,
          cantantes solistas y bandas en vivo.
        </Paragraph>
        <Button>más info</Button>
      </main>

      <footer>
        <p>made by Mariano Guillaume</p>
      </footer>
    </div>
  );
}
